export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOAD_ITEMS = 'LOAD_ITEMS';
export const LOAD_ITEMS_FAIL = 'LOAD_ITEMS_FAIL';
export const LOGOUT = 'LOGOUT';
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';
export const ORDERS_LOADED = 'ORDERS_LOADED';
export const ORDERS_ERROR = 'ORDERS_ERROR';
export const PROFILE_UPDATED = 'PROFILE_UPDATED';
export const PROFILE_UPDATED_ERROR = 'PROFILE_UPDATED_ERROR';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

//admin
export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL';
export const LOAD_ORDERS = 'LOAD_ORDERS';
export const LOAD_ORDERS_FAIL = 'LOAD_ORDERS_FAIL';